### ISSUE TITLE
What is the intended workflow for lnt/test-suite/etc

### ISSUE THREAD

**Issue by danilaml** [jyknight/llvm-git-migration#5]
What is the intended workflow for using this tool to migrate projects to their new official git repositories that have not become part of the monorepo (like `lnt` or `test-suite`)?

**Comment by jyknight** [comment]
It doesn't handle those at the moment. Do you have significant downstream forks of these other projects?

If you only have small work in progress patches, the simplest solution is to just use "git rebase" to move it to the new repository.

**Comment by danilaml** [comment]
@jyknight yeah, I have a long-living fork (i.e. lots of personal commits with occasional upstream merges), otherwise I wouldn't be interested in the script (manually redoing all the merges and resolving all numerous conflicts again and again would be a nightmare).

**Comment by jyknight** [comment]
The script supports this now.

**Comment by danilaml** [comment]
Thanks, seems to be working fine, although I had to manually specify `--source-kind auxilliary` since it detected commits from potentially two repos instead of one (zorg "got in the way").
